#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

export ASL_TOUCH_UI="${ASL_TOUCH_UI:-1}"
export ASL_TOUCH_FULLSCREEN="${ASL_TOUCH_FULLSCREEN:-1}"
export ASL_DEMO_MODE="${ASL_DEMO_MODE:-1}"
export ASL_DEMO_PHRASE_SNAP="${ASL_DEMO_PHRASE_SNAP:-1}"
export ASL_DEMO_PHRASE_PRESET="${ASL_DEMO_PHRASE_PRESET:-presentation_dual_phrase}"
export ASL_DEMO_VOCAB="${ASL_DEMO_VOCAB:-HELLO,ME,GOOD,THANK_YOU,NEED,DRINK}"
export ASL_DEMO_TOKEN_REMAP="${ASL_DEMO_TOKEN_REMAP:-}"

# Slightly easier live capture defaults for the constrained assisted phrase.
export ASL_SINGLE_SIGN_CAPTURE="${ASL_SINGLE_SIGN_CAPTURE:-0}"
export ASL_SUPPRESS_IDLE_HAND="${ASL_SUPPRESS_IDLE_HAND:-1}"
export ASL_MODEL_REJECT_CONFIDENCE="${ASL_MODEL_REJECT_CONFIDENCE:-0.30}"
export ASL_MIN_CONFIDENCE="${ASL_MIN_CONFIDENCE:-0.55}"
export ASL_COMMIT_MIN_CONFIDENCE="${ASL_COMMIT_MIN_CONFIDENCE:-0.68}"
export ASL_STABLE_FRAMES="${ASL_STABLE_FRAMES:-5}"
export ASL_EMIT_COOLDOWN_FRAMES="${ASL_EMIT_COOLDOWN_FRAMES:-8}"
export ASL_PAUSE_FRAMES="${ASL_PAUSE_FRAMES:-10}"
export ASL_TRANSITION_MOTION_THRESHOLD="${ASL_TRANSITION_MOTION_THRESHOLD:-0.028}"
export ASL_COMMIT_MOTION_THRESHOLD="${ASL_COMMIT_MOTION_THRESHOLD:-0.020}"
export ASL_MOTION_SETTLE_FRAMES="${ASL_MOTION_SETTLE_FRAMES:-1}"
export ASL_HAND_HOLD_FRAMES="${ASL_HAND_HOLD_FRAMES:-1}"
export ASL_BODY_HOLD_FRAMES="${ASL_BODY_HOLD_FRAMES:-0}"
export ASL_POSE_SMOOTHING="${ASL_POSE_SMOOTHING:-0.35}"
export ASL_CAMERA_FAST_MODE="${ASL_CAMERA_FAST_MODE:-1}"
export ASL_CAMERA_WIDTH="${ASL_CAMERA_WIDTH:-640}"
export ASL_CAMERA_HEIGHT="${ASL_CAMERA_HEIGHT:-480}"
export ASL_PROCESS_WIDTH="${ASL_PROCESS_WIDTH:-384}"
export ASL_PROCESS_HEIGHT="${ASL_PROCESS_HEIGHT:-216}"
export ASL_PROCESS_EVERY_N="${ASL_PROCESS_EVERY_N:-2}"
export ASL_CAMERA_ZOOM="${ASL_CAMERA_ZOOM:-1.15}"

cd "${REPO_ROOT}"
exec ./scripts/run_ui_pi.sh
