#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

CAMERA_INDEX="${ASL_CAMERA_INDEX:-0}"
PYTHON_BIN="${PYTHON_BIN:-${REPO_ROOT}/.venv/bin/python}"
# Optional camera tuning knobs (override when launching):
# ASL_CAMERA_WIDTH / ASL_CAMERA_HEIGHT / ASL_CAMERA_FPS
# ASL_PROCESS_WIDTH / ASL_PROCESS_HEIGHT / ASL_PROCESS_EVERY_N
# ASL_CAMERA_ZOOM (1.0 = no crop, 1.2 = mild zoom, 1.5+ strong zoom)
# ASL_CAMERA_BUFFER_SIZE (1 recommended for lower latency)
# ASL_POSE_SMOOTHING / ASL_HAND_HOLD_FRAMES / ASL_BODY_HOLD_FRAMES
CAMERA_WIDTH="${ASL_CAMERA_WIDTH:-640}"
CAMERA_HEIGHT="${ASL_CAMERA_HEIGHT:-480}"
CAMERA_FPS="${ASL_CAMERA_FPS:-30}"
PROCESS_WIDTH="${ASL_PROCESS_WIDTH:-384}"
PROCESS_HEIGHT="${ASL_PROCESS_HEIGHT:-216}"
PROCESS_EVERY_N="${ASL_PROCESS_EVERY_N:-2}"
CAMERA_ZOOM="${ASL_CAMERA_ZOOM:-1.0}"
CAMERA_BUFFER_SIZE="${ASL_CAMERA_BUFFER_SIZE:-1}"
POSE_SMOOTHING="${ASL_POSE_SMOOTHING:-0.40}"
HAND_HOLD_FRAMES="${ASL_HAND_HOLD_FRAMES:-1}"
BODY_HOLD_FRAMES="${ASL_BODY_HOLD_FRAMES:-0}"
TOUCH_UI="${ASL_TOUCH_UI:-1}"
TOUCH_FULLSCREEN="${ASL_TOUCH_FULLSCREEN:-1}"
TTS_ALSA_DEVICE="${ASL_TTS_ALSA_DEVICE:-default:CARD=wm8960soundcard}"
DEMO_MODE="${ASL_DEMO_MODE:-0}"
DEMO_TOKEN_REMAP="${ASL_DEMO_TOKEN_REMAP:-}"
SINGLE_SIGN_CAPTURE="${ASL_SINGLE_SIGN_CAPTURE:-0}"
SUPPRESS_IDLE_HAND="${ASL_SUPPRESS_IDLE_HAND:-1}"
MODEL_REJECT_CONFIDENCE="${ASL_MODEL_REJECT_CONFIDENCE:-0.40}"
MIN_CONFIDENCE="${ASL_MIN_CONFIDENCE:-0.70}"
COMMIT_MIN_CONFIDENCE="${ASL_COMMIT_MIN_CONFIDENCE:-0.82}"
STABLE_FRAMES="${ASL_STABLE_FRAMES:-8}"
EMIT_COOLDOWN_FRAMES="${ASL_EMIT_COOLDOWN_FRAMES:-14}"
PAUSE_FRAMES="${ASL_PAUSE_FRAMES:-14}"
AUTO_STOP_NO_HAND_FRAMES="${ASL_AUTO_STOP_NO_HAND_FRAMES:-4}"
TRANSITION_MOTION_THRESHOLD="${ASL_TRANSITION_MOTION_THRESHOLD:-0.020}"
COMMIT_MOTION_THRESHOLD="${ASL_COMMIT_MOTION_THRESHOLD:-0.014}"
MOTION_SETTLE_FRAMES="${ASL_MOTION_SETTLE_FRAMES:-2}"
QT_PLATFORM="${QT_QPA_PLATFORM:-xcb}"

if ! command -v libcamerify >/dev/null 2>&1; then
  echo "Error: libcamerify not found. Install Raspberry Pi camera apps/tools first." >&2
  exit 1
fi

if [[ ! -x "${PYTHON_BIN}" ]]; then
  echo "Error: Python interpreter not executable: ${PYTHON_BIN}" >&2
  exit 1
fi

cd "${REPO_ROOT}"
ASL_CAMERA_INDEX="${CAMERA_INDEX}" \
ASL_CAMERA_WIDTH="${CAMERA_WIDTH}" \
ASL_CAMERA_HEIGHT="${CAMERA_HEIGHT}" \
ASL_CAMERA_FPS="${CAMERA_FPS}" \
ASL_PROCESS_WIDTH="${PROCESS_WIDTH}" \
ASL_PROCESS_HEIGHT="${PROCESS_HEIGHT}" \
ASL_PROCESS_EVERY_N="${PROCESS_EVERY_N}" \
ASL_CAMERA_ZOOM="${CAMERA_ZOOM}" \
ASL_CAMERA_BUFFER_SIZE="${CAMERA_BUFFER_SIZE}" \
ASL_POSE_SMOOTHING="${POSE_SMOOTHING}" \
ASL_HAND_HOLD_FRAMES="${HAND_HOLD_FRAMES}" \
ASL_BODY_HOLD_FRAMES="${BODY_HOLD_FRAMES}" \
ASL_TOUCH_UI="${TOUCH_UI}" \
ASL_TOUCH_FULLSCREEN="${TOUCH_FULLSCREEN}" \
ASL_TTS_ALSA_DEVICE="${TTS_ALSA_DEVICE}" \
ASL_DEMO_MODE="${DEMO_MODE}" \
ASL_DEMO_TOKEN_REMAP="${DEMO_TOKEN_REMAP}" \
ASL_SINGLE_SIGN_CAPTURE="${SINGLE_SIGN_CAPTURE}" \
ASL_SUPPRESS_IDLE_HAND="${SUPPRESS_IDLE_HAND}" \
ASL_MODEL_REJECT_CONFIDENCE="${MODEL_REJECT_CONFIDENCE}" \
ASL_MIN_CONFIDENCE="${MIN_CONFIDENCE}" \
ASL_COMMIT_MIN_CONFIDENCE="${COMMIT_MIN_CONFIDENCE}" \
ASL_STABLE_FRAMES="${STABLE_FRAMES}" \
ASL_EMIT_COOLDOWN_FRAMES="${EMIT_COOLDOWN_FRAMES}" \
ASL_PAUSE_FRAMES="${PAUSE_FRAMES}" \
ASL_AUTO_STOP_NO_HAND_FRAMES="${AUTO_STOP_NO_HAND_FRAMES}" \
ASL_TRANSITION_MOTION_THRESHOLD="${TRANSITION_MOTION_THRESHOLD}" \
ASL_COMMIT_MOTION_THRESHOLD="${COMMIT_MOTION_THRESHOLD}" \
ASL_MOTION_SETTLE_FRAMES="${MOTION_SETTLE_FRAMES}" \
QT_QPA_PLATFORM="${QT_PLATFORM}" \
libcamerify "${PYTHON_BIN}" -m ui.main
